### ISSUE TITLE
Error 8500: The requested property does not exist.

### ISSUE THREAD

**Issue by nandastone** [dcondrey/DetectFontsinPSD#1]
**MacOS**
**Adobe Photoshop CC 2017 (20161012.r.53 x64)**

```
Line: 50
->              var n = layerStyles.getObjectValue(countStyles).getObjectValue(stringIDToTypeID('textStyle')).getString(stringIDToTypeID('fontPostScriptName'));
```

Has something changed in the new version of PS?

**Comment by agrath** [comment]
@nandastone I think this is an issue in the way the PSD is structured. I've just raised a pull request that fixes the script
